# Common build configuration inherited by
# all other configurations
[build]
  command = "npm run test && npm run generate"
  publish = "dist"

# Environment variable used by production branch i.e master
[context.production]
  command = "cd functions/take-screenshot && npm i && cd ../../ && NODE_ENV=production npm run generate"
  functions = "functions/"

[context.production.environment]
  API_BASE_URL = "https://api.coronatracker.com"
  BASE_URL = "https://www.coronatracker.com"
  GENERATE_ROUTES = "true"

# Environment variable overriden for staging branch
[context.staging]
  command = "cd functions/take-screenshot && npm i && cd ../../ && NODE_ENV=production npm run generate"
  functions = "functions/"

[context.staging.environment]
  API_BASE_URL = "https://api.staging.coronatracker.com"
  BASE_URL = "https://staging.coronatracker.com"
  GA_ID = "UA-xxxxxxxxx-x"
  GENERATE_ROUTES = "true"

# Environment variable overriden for dev branch
[context.dev]
  command = "cd functions/take-screenshot && npm i && cd ../../ && npm run test && npm run generate"
  functions = "functions/"

[context.dev.environment]
  API_BASE_URL = "https://api.staging.coronatracker.com"
  BASE_URL = "https://staging.coronatracker.com"
  GA_ID = "UA-xxxxxxxxx-x"
  GENERATE_ROUTES = "false"

# Environment variable overriden for "feature/netlify-function" branch
[context."feature/netlify-function"]
  command = "cd functions/take-screenshot && npm i && cd ../../ && npm run test && npm run generate"
  functions = "functions/"

[context."feature/netlify-function".environment]
  API_BASE_URL = "https://api.staging.coronatracker.com"
  BASE_URL = "https://staging.coronatracker.com"
  GA_ID = "UA-xxxxxxxxx-x"
  GENERATE_ROUTES = "false"

# Environment variable overriden for deploy-preview's
# Deploy preview's are generated by pull/merge requests
[context.deploy-preview]
[context.deploy-preview.environment]
  API_BASE_URL = "https://api.staging.coronatracker.com"
  BASE_URL = "https://staging.coronatracker.com"
  GA_ID = "UA-xxxxxxxxx-x"
  GENERATE_ROUTES = "false"

# Environment variable overriden for branch deploys
# Branch deployes are applicable for non-master branches
# Such as staging, dev branches
[context.branch-deploy]
[context.branch-deploy.environment]
  API_BASE_URL = "https://api.staging.coronatracker.com"
  BASE_URL = "https://staging.coronatracker.com"
  GA_ID = "UA-xxxxxxxxx-x"
  GENERATE_ROUTES = "false"

[[redirects]]
  from = "/blog"
  to = "https://blog.coronatracker.com/blog/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/blog/*/"
  to = "https://blog.coronatracker.com/blog/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/blog/*"
  to = "https://blog.coronatracker.com/blog/:splat/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
